version: '3'
services:
  web:
    build: ./web
    ports:
      - 3000:3000
      - 5050:5050
    depends_on:
      - app
      - db
    links:
      - app
    network_mode: "host"
    environment:
      - VITE_BASE_API=${vite_base_api}
  app:
    build: ./app
    ports:
      - 8080:8080
    environment:
      - GRADLE_OPTS=${gradle_opts}
      - spring_profiles_active=${spring_profiles_active}
    depends_on:
      - db
    links:
      - db
    network_mode: "host"
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=works_on_my_machine
    volumes:
      - .data:/var/lib/postgresql/data:Z
    
