version: '3'
services:
  web:
    build: ./web
    expose:
      - 3000
    depends_on:
      - app
      - db
  app:
    build: ./app
    expose:
      - 8080
    depends_on:
      - db
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - .data:/var/lib/postgresql/data:rw